apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: init-file
  namespace: {{ .Values.namespace }}  
  labels:
    app: postgresdb
data:
  init-file.sql: |     
    CREATE TABLE reservations (                   
      id serial NOT NULL primary key,
      cre_date timestamp not null,
      item_id integer not null,
      data varchar(2000) null
     );     
    CREATE TABLE payments (                   
      id serial NOT NULL primary key,
      cre_date timestamp not null,
      summ integer not null,
      returned integer not null,
      data varchar(2000) null
     );     
    CREATE TABLE deliveries (                   
      id serial NOT NULL primary key,
      cre_date timestamp not null,
      date date not null,
      hour integer not null,
      data varchar(2000) null
     );
    CREATE UNIQUE INDEX uidx_date_hour ON deliveries (date, hour);
    CREATE UNIQUE INDEX uidx_item_id ON reservations (item_id);

